name: Deploy Website production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Configure Git user
        run: |
          git config --global user.name "Nemeos BOT"
          git config --global user.email "githubbot@nemeos.finance"

      - name: Deploy app
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_ACCESS_TOKEN}@github.com/nemeos/nemeos.github.io.git
          yarn deploy
